config/routes.rb
Rails.application.routes.draw do
  root 'todo_lists#index'
  resources :todo_lists, except: :show do
    resources :tasks, except: :show, module: :todo_lists do
      member do
        put 'status_update/:status', to: 'tasks#status_update', as: :status_update
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :todo_list
  STATUSES = { todo: 0, doing: 1, done: 2 }.freeze
  validates :name, presence: true, length: { maximum: 200 }
  validates :status, presence: true, on: :update
  enum status: STATUSES, _prefix: :status

  ransacker :status, formatter: proc { |v| statuses[v] }
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :tasks, dependent: :destroy

  validates :name, presence: true, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  rescue_from ActiveRecord::RecordNotFound do
    render :not_found, status: :not_found
  end
end

app/controllers/todo_lists/tasks_controller.rb
module TodoLists
  class TasksController < ApplicationController
    before_action :set_todo_list
    before_action :set_task, only: %i[edit update status_update destroy]

    def index
      @q = @todo_list.tasks.ransack(params[:q])
      @q.sorts = 'id desc' if @q.sorts.empty?
      @tasks = @q.result.page(params[:page]).per(params[:size])
    end

    def new
      @task = Task.new
    end

    def create
      @task = Task.new(task_params.merge(todo_list_id: @todo_list.id))
      if @task.save
        redirect_to todo_list_tasks_path(todo_list_id: @todo_list.id), notice: 'Task was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit; end

    def status_update
      @task.update(status: params[:status])
      redirect_to todo_list_tasks_path(todo_list_id: @todo_list.id), notice: 'Task status was successfully updated.'
    rescue ArgumentError => e
      redirect_to todo_list_tasks_path(todo_list_id: @todo_list.id), alert: e.message
    end

    def update
      if @task.update(task_params)
        redirect_to todo_list_tasks_path(todo_list_id: @todo_list.id), notice: 'Task was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @task.destroy
      redirect_to todo_list_tasks_path(todo_list_id: @todo_list.id), notice: 'Task was successfully destroyed.'
    end

    private

    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

    def set_task
      @task = @todo_list.tasks.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :status)
    end
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: %i[edit update destroy]

  def index
    @q = TodoList.ransack(params[:q])
    @q.sorts = 'id desc' if @q.sorts.empty?
    @todo_lists = @q.result.page(params[:page]).per(params[:size])
  end

  def new
    @todo_list = TodoList.new
  end

  def create
    @todo_list = TodoList.new(todo_list_params)
    if @todo_list.save
      redirect_to todo_list_tasks_path(todo_list_id: @todo_list.id), notice: 'TodoList was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @todo_list.update(todo_list_params)
      redirect_to todo_list_tasks_path(todo_list_id: @todo_list.id), notice: 'TodoList was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @todo_list.destroy
    redirect_to todo_lists_path, notice: 'TodoList was successfully destroyed.'
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:id])
  end

  def todo_list_params
    params.require(:todo_list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_lists/tasks_helper.rb
module TodoLists
  module TasksHelper
    def class_btn_status(status)
      class_btn = {
        'done' => 'btn-success',
        'doing' => 'btn-warning',
        'todo' => 'btn-danger'
      }
      "btn btn-sm #{class_btn[status.to_s]}"
    end

    def statics_tasks(status:, todo_list: nil)
      tasks = if todo_list.present?
                todo_list.tasks
              else
                Task
              end
      total = tasks.where(status: status).count
      content_tag(:span, "#{pluralize(total, 'task')} in #{status}", class: class_btn_status(status))
    end
  end
end

app/views/application/not_found.html.erb
<h1>404</h1>

app/views/layouts/_notice.html.erb
<% if flash[:notice].present? %>
  <div class='container py-5 h-100'>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <strong>Great!</strong> <%= flash[:notice] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% elsif flash[:alert] %>
  <div class='container py-5 h-100'>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong>Something wrong!</strong> <%= flash[:alert] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= render partial: 'layouts/notice' if flash.present? %>
    <div class="container py-5 h-100">
      <%= yield %>
    </div>
    <%= javascript_importmap_tags %>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todo_lists/_form.html.erb
<%= simple_form_for @todo_list do |f| %>
  <div class="input-group mb-3">
    <%= f.input :name, placeholder: 'Todo list name', input_html: { maxlength: 200, class: 'form-control' }, wrapper: false, label: false %>
    <%= f.button :submit, { class: 'btn btn-primary' } %>
  </div>
<% end %>

app/views/todo_lists/_search_form.html.erb
<%= simple_form_for(@q, method: :get, url: todo_lists_path) do |f| %>
  <div class='input-group mb-3 py-3'>
    <%= f.input :name_cont, placeholder: 'Search TodoList',
        input_html: { maxlength: 200, class: 'form-control' }, wrapper: false, label: false %>
    <%= f.submit 'Search', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/todo_lists/_statics_task.html.erb
<div class='row py-5'>
  <div class='col'>
  <% Task::STATUSES.keys.map(&:to_s).each do |status| %>
      <%= statics_tasks(status) %>
  <% end %>
  </div>
</div>

app/views/todo_lists/edit.html.erb
<h1>Update TodoList: <%= @todo_list.name %></h1>
<%= render 'form' %>

app/views/todo_lists/index.html.erb
<h1>TodoLists</h1>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">TodoLists</li>
  </ol>
</nav>
<%= link_to 'Add TodoList', new_todo_list_path, class: 'btn btn-primary' %>
<%= render 'todo_lists/shared/statics_task' %>
<%= render 'search_form' %>
<table class="table">
  <thead>
    <tr>
      <th scope="col"><%= sort_link(@q, :id, '#', default_order: :desc) %></th>
      <th scope="col"><%= sort_link(@q, :name, 'Name') %></th>
      <th scope="col">Tasks</th>
      <th scope="col" class='text-center'>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @todo_lists.each do |todo_list| %>
    <tr>
      <th scope="row"><%= todo_list.id %></th>
      <td><%= todo_list.name %></td>
      <td><%= todo_list.tasks.count %></td>
      <td class='text-center'>
        <%= link_to 'view', todo_list_tasks_path(todo_list_id: todo_list.id), class: 'btn btn-sm btn-primary' %>
        <%= link_to 'delete', todo_list_path(todo_list), method: :delete, data: { confirm: 'are you sure?' }, class: 'btn btn-sm btn-danger' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class='pagination-outer w-100 text-center'>
  <%= paginate @todo_lists %>
</div>

app/views/todo_lists/new.html.erb
<h1>Create new TodoList</h1>
<%= render 'form' %>

app/views/todo_lists/shared/_statics_task.html.erb
<div class='row py-5'>
  <div class='col'>
  <% Task::STATUSES.keys.map(&:to_s).each do |status| %>
      <%= statics_tasks(todo_list: @todo_list, status: status) %>
  <% end %>
  </div>
</div>

app/views/todo_lists/tasks/_group_input.html.erb
<div class="input-group mb-3">
  <%= f.input :name, placeholder: 'Task name', input_html: { maxlength: 200, class: 'form-control' }, wrapper: false, label: false %>
  <%= f.button :submit, { class: 'btn btn-primary' } %>
</div>

app/views/todo_lists/tasks/_search_form.html.erb
<%= simple_form_for(@q, method: :get, url: todo_list_tasks_path(todo_list_id: @todo_list.id)) do |f| %>
  <div class='input-group mb-3 py-3'>
    <%= f.input :name_cont, placeholder: 'Search task',
        input_html: { maxlength: 200, class: 'form-control' }, wrapper: false, label: false %>
    <%= f.input :status_eq, collection: Task::STATUSES.keys.map(&:to_s),
        label: false, input_html: { class: 'form-select'}, include_blank: true, prompt: 'Status' %>
    <%= f.submit 'Search', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/todo_lists/tasks/edit.html.erb
<h1>TodoList: <%= @todo_list.name %></h1>
<h2>Edit task: <%= @task.name %></h2>
<%= simple_form_for(@task, method: :put, url: todo_list_task_path(todo_list_id: @todo_list.id, id: @task.id)) do |f| %>
  <%= render partial: 'group_input', locals: { f: f } %>
<% end %>

app/views/todo_lists/tasks/index.html.erb
<h1><%= @todo_list.name %></h1>
<%= render partial: 'todo_lists/shared/statics_task' %>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'TodoLists', todo_lists_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @todo_list.name %></li>
  </ol>
</nav>
<%= link_to 'Add task', new_todo_list_task_path(todo_list_id: @todo_list.id), class: 'btn btn-primary' %>
<%= render partial: 'search_form' %>
<table class="table">
  <thead>
    <tr>
      <th scope="col"><%= sort_link(@q, :id, '#', default_order: :desc) %></th>
      <th scope="col"><%= sort_link(@q, :name, 'Name') %></th>
      <th scope="col"><%= sort_link(@q, :status, 'Status') %></th>
      <th scope="col" class='text-center'>Status actions</th>
      <th scope="col" class='text-center'>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <th scope="row"><%= task.id %></th>
      <td><%= task.name %></td>
      <td><%= content_tag(:p, task.status, class: class_btn_status(task.status))  %></td>
      <td class='text-center'>
        <% Task::STATUSES.keys.each do |status| %>
          <%= link_to status, status_update_todo_list_task_path(todo_list_id: @todo_list.id, id: task.id, status: status), method: :put, class: class_btn_status(status) unless status.to_s == task.status %>
        <% end %>
      </td>
       <td class='text-center'>
        <%= link_to 'edit', edit_todo_list_task_path(todo_list_id: @todo_list.id, id: task.id), class: 'btn btn-sm btn-primary' %>
        <%= link_to 'delete', todo_list_task_path(todo_list_id: @todo_list.id, id: task.id), method: :delete, data: { confirm: 'are you sure?' }, class: 'btn btn-sm btn-danger' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class='pagination-outer w-100 text-center'>
  <%= paginate @tasks %>
</div>

app/views/todo_lists/tasks/new.html.erb
<h1>TodoList: <%= @todo_list.name %></h1>
<h2>New Task</h2>
<%= simple_form_for(@task, method: :post, url: todo_list_tasks_path(todo_list_id: @todo_list.id)) do |f| %>
  <%= render partial: 'group_input', locals: { f: f } %>
<% end %>